"""LTX-Video image-to-video skill.

Generates a short video from a static image (optionally guided by a text
prompt) using Lightricks' LTX-Video 0.9.8 13B distilled model.

Runs each stage of generation (text encoding, denoising, safety-screening +
export) in its own short-lived subprocess. On macOS, only *process exit*
reliably returns a component's resident memory to the OS -- there is no
in-process call that does the same. Manual reclamation calls such as
del, gc.collect(), and torch.mps.empty_cache() are deliberately not used
anywhere in this file: process exit is unconditional, complete, and free,
so those calls would only run microseconds before the process dies anyway.
That is why the three stages are three separate OS processes rather than
three phases of one long-lived one.

Why this exists (2026-08-25 incident):
An earlier revision of this module loaded the whole pipeline in a single
process and relied on diffusers' enable_model_cpu_offload()
(shuffling submodules between "cpu" and "mps" on demand) to keep the model
resident under the MPS ceiling. On Apple Silicon that helper is a no-op for
total DRAM *residency*: CPU and GPU share one physical memory pool, so
changing which device owns a tensor changes bookkeeping, not occupancy.
Combined with PyTorch's default MPS high watermark ratio of 1.7 -- which
permits 1.7 x 37.44 GiB = 63.65 GiB of allocation on this 48 GiB host -- the
process was free to keep growing until the machine froze hard, requiring a
forced reboot.

The old docstring's memory numbers were also wrong. Measured, correct
figures:

    component                    on-disk    on-disk dtype   resident @ bf16
    transformer (13.043B params)  24.29 GiB  BF16            24.29 GiB
    text_encoder / T5 (4.762B)    17.74 GiB  F32              8.87 GiB
    vae (1.247B params)            2.32 GiB  BF16             2.32 GiB
    total                         44.36 GiB                  35.48 GiB

35.48 GiB does fit under the 37.44 GiB MPS ceiling, but that leaves only
1.96 GiB for activations and roughly 12.5 GiB for the OS -- too tight for a
single process holding all three components at once. Splitting the work
into stage1 (text encoder only, 8.87 GiB), stage2 (transformer + vae, 26.61
GiB, no text encoder ever loaded), and stage3 (no diffusion weights at all)
means each process's peak footprint is far below the combined figure, and
each one's memory is unconditionally returned to the OS the moment it exits.

Works on Apple Silicon (MPS) and falls back to CPU. CUDA is used if present.

Usage:
    python3 ltx_video_skill.py <image_path> ["<prompt>"] [output_path]

    # or as a module:
    from ltx_video_skill import generate_video
    frames = generate_video("robot.png", "the robot waves", output_path="robot.mp4")

Environment:
    HF_TOKEN  Hugging Face access token (optional; omitted falls back to any
              token cached locally by `huggingface-cli login`, or anonymous
              access for public repos).

Generated output is screened by content_safety.assert_frames_safe (on a
sample of frames) before being saved or returned; a positive verdict raises
ContentSafetyError and saves nothing.

This module intentionally does not import torch, diffusers, transformers,
or content_safety at import time -- those imports, and all model loading,
happen inside the per-stage functions below, each of which only ever runs
inside its own subprocess.
"""

import argparse
import datetime
import glob
import json
import os
import shutil
import subprocess
import sys
import uuid

_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
if _THIS_DIR not in sys.path:
    sys.path.insert(0, _THIS_DIR)

import mps_guard

MODEL_ID = "Lightricks/LTX-Video-0.9.8-13B-distilled"  # unchanged

# VAE spatial_compression_ratio is 32: both dims must be multiples of it.
DEFAULT_WIDTH = 704   # 704 / 32 == 22
DEFAULT_HEIGHT = 480  # 480 / 32 == 15
# VAE temporal_compression_ratio is 8: (num_frames - 1) must be a multiple.
DEFAULT_NUM_FRAMES = 49  # (49 - 1) % 8 == 0; 49 frames @ 24 fps == 2.04 s
DEFAULT_STEPS = 8
DEFAULT_GUIDANCE = 1.0
DEFAULT_FPS = 24
DEFAULT_FRAME_RATE = 24
DEFAULT_NEGATIVE_PROMPT = "worst quality, inconsistent motion, blurry, jittery, distorted"
MAX_SEQUENCE_LENGTH = 256
RUNS_SUBDIR = "generated/ltx_runs"
# width/height must also be multiples of 16 for the cv2 mp4v writer used by
# stage3's export fallback (see _stage3_screen_and_export).

# Machine-generated by tests/measure_ltx_ceiling.py --reduce. Absent/stale is
# tolerated (see _check_ceiling): mps_guard remains the runtime backstop.
CEILING_TABLE_PATH = os.path.join(_THIS_DIR, "ltx_ceiling.json")
# Each non-zero-index condition adds one latent frame's worth of transformer
# tokens (C3 -- (H/32)x(W/32) tokens, attention scales ~O(tokens^2)); this
# converts that token cost back into an equivalent number of output frames
# for the ceiling-gate comparison (Section 8.4).
_CEILING_FRAMES_PER_CONDITION = 8


def _pick_device():
    """Choose the best available device: CUDA > MPS (Apple GPU) > CPU."""
    import torch

    if torch.cuda.is_available():
        return torch.device("cuda")
    if torch.backends.mps.is_available():
        return torch.device("mps")
    return torch.device("cpu")


def _pick_dtype(device):
    """Use bfloat16 on GPU (CUDA/MPS), float32 on CPU for stability."""
    import torch

    return torch.bfloat16 if device.type in ("cuda", "mps") else torch.float32


def _validate_geometry(width, height, num_frames):
    """Raise ValueError naming the offending value and the rule it broke."""
    if width % 32 != 0:
        raise ValueError(
            "width=%d must satisfy width %% 32 == 0 (VAE spatial_compression_ratio 32)" % width
        )
    if height % 32 != 0:
        raise ValueError(
            "height=%d must satisfy height %% 32 == 0 (VAE spatial_compression_ratio 32)" % height
        )
    if (num_frames - 1) % 8 != 0:
        raise ValueError(
            "num_frames=%d must satisfy (num_frames - 1) %% 8 == 0 "
            "(VAE temporal_compression_ratio 8)" % num_frames
        )
    if width % 16 != 0:
        raise ValueError(
            "width=%d must satisfy width %% 16 == 0 (required by the cv2 mp4v writer)" % width
        )
    if height % 16 != 0:
        raise ValueError(
            "height=%d must satisfy height %% 16 == 0 (required by the cv2 mp4v writer)" % height
        )


def _normalized_conditions(request):
    """Return the list of condition dicts for a request, tolerating the
    legacy single-image shape. Never mutates `request`."""
    conditions = request.get("conditions")
    if conditions:
        return conditions
    return [{"image_path": request["image_path"], "frame_index": 0, "strength": 1.0}]


def _validate_conditions(conditions, num_frames):
    """Raise ValueError naming the offending value and the rule it broke."""
    # 1. Non-empty (always true by construction; defensive).
    if len(conditions) < 1:
        raise ValueError("conditions must be a non-empty list")

    # 2. frame_index type + range. No 8-alignment required (C1): image
    # conditions are placed at raw pixel coordinates, not floored to the
    # latent grid.
    for c in conditions:
        frame_index = c["frame_index"]
        if not isinstance(frame_index, int) or not (0 <= frame_index <= num_frames - 1):
            raise ValueError(
                "frame_index=%r is out of range: must satisfy 0 <= frame_index <= num_frames-1 = %d"
                % (frame_index, num_frames - 1)
            )

    # 3. strength type + range.
    for c in conditions:
        strength = c["strength"]
        if not isinstance(strength, (int, float)) or not (0.0 <= strength <= 1.0):
            raise ValueError(
                "strength=%r is out of range for %s: must satisfy 0.0 <= strength <= 1.0"
                % (strength, c["image_path"])
            )

    # 4. Local file existence. URLs are resolved by load_image in stage 2,
    # so they are not existence-checked here.
    for c in conditions:
        image_path = c["image_path"]
        if "://" not in image_path and not os.path.isfile(image_path):
            raise ValueError("conditioning image not found: %s" % image_path)

    # 5. No duplicate frame_index: two conditions at the same index would
    # either overwrite the same hard latent slot or stack ambiguous soft
    # tokens; refusing is deterministic and safe.
    seen_frame_indices = set()
    for c in conditions:
        frame_index = c["frame_index"]
        if frame_index in seen_frame_indices:
            raise ValueError(
                "duplicate frame_index=%d: each condition must target a distinct output frame"
                % frame_index
            )
        seen_frame_indices.add(frame_index)


_KEYFRAME_ERR = ("malformed --keyframe %r: expected PATH:INDEX[:STRENGTH] "
                 "where INDEX is an integer and STRENGTH is a float in [0.0,1.0]")


def _parse_keyframe_spec(spec):
    """Parse 'PATH:INDEX[:STRENGTH]' -> dict. Raise ValueError on malformed input."""
    parts = spec.split(":")
    if len(parts) < 2:
        raise ValueError(_KEYFRAME_ERR % spec)

    def _is_int(s):
        try:
            int(s)
            return True
        except ValueError:
            return False

    def _is_float(s):
        try:
            float(s)
            return True
        except ValueError:
            return False

    # Try PATH:INDEX:STRENGTH (last two numeric), else PATH:INDEX (last numeric).
    if len(parts) >= 3 and _is_int(parts[-2]) and _is_float(parts[-1]):
        return {
            "image_path": ":".join(parts[:-2]),
            "frame_index": int(parts[-2]),
            "strength": float(parts[-1]),
        }
    if _is_int(parts[-1]):
        return {
            "image_path": ":".join(parts[:-1]),
            "frame_index": int(parts[-1]),
            "strength": 1.0,
        }
    raise ValueError(_KEYFRAME_ERR % spec)


def _check_ceiling(width, height, num_frames, conditions, wide):
    """Refuse (raise mps_guard.HostSafetyError) a request that exceeds the
    measured non-wide ceiling. No-op when wide=True or the table is absent.

    The measured table (CEILING_TABLE_PATH) is generated at fraction 0.82
    (non-wide) only -- there is no 0.87 (--wide) table yet (Section 8.7), so
    a wide=True request is never checked against it and is gated solely by
    mps_guard.
    """
    if wide:
        return

    try:
        with open(CEILING_TABLE_PATH) as f:
            table = json.load(f)
    except (OSError, ValueError):
        sys.stderr.write(
            "[ltx_video_skill] note: %s absent/unreadable; skipping ceiling pre-check "
            "(mps_guard remains the backstop)\n" % CEILING_TABLE_PATH
        )
        return

    ceiling = table["ceiling"]
    key = "%dx%d" % (width, height)
    # measured_resolutions: every WxH the sweep actually ran, regardless of
    # outcome (Section 8.3 step 3 below). Absent on an older table -- that
    # older table predates this field, so `measured` is empty, step 3 never
    # fires, and the lookup falls through to the pre-existing dominated-by
    # -smaller-resolution rule exactly as before (no crash, no behavior
    # change for such a table).
    measured = set(table.get("meta", {}).get("measured_resolutions", []))

    if key in ceiling:
        max_frames = ceiling[key]
    elif key in measured:
        # This resolution WAS measured, but its lightest run still exceeded
        # the safety margin, so the reducer omitted it from `ceiling`. It
        # must be refused outright, never bounded by a smaller resolution's
        # ceiling -- that dominated-by-smaller bound is only valid for
        # resolutions that were never run at all (see step 4 below).
        margin_frac = table.get("meta", {}).get("safety_margin_frac")
        margin_phrase = (
            "the %.0f%% safety margin" % (margin_frac * 100)
            if margin_frac is not None
            else "the safety margin"
        )
        raise mps_guard.HostSafetyError(
            "HOST SAFETY REFUSAL: %dx%d was measured and its lightest run still exceeds %s\n"
            "of the non-wide (0.82) budget, so it has no supported frame count. Choose a smaller\n"
            "resolution or pass --wide for the higher (0.87) budget."
            % (width, height, margin_phrase)
        )
    else:
        candidates = []
        for measured_key, measured_frames in ceiling.items():
            measured_w, measured_h = (int(p) for p in measured_key.split("x"))
            if measured_w <= width and measured_h <= height:
                candidates.append(measured_frames)
        if not candidates:
            raise mps_guard.HostSafetyError(
                "HOST SAFETY REFUSAL: resolution %dx%d has no measured ceiling entry and no smaller measured\n"
                "resolution to bound it. Measured resolutions: %s. Run the sweep\n"
                "(tests/measure_ltx_ceiling.py) for this resolution, choose a measured resolution, or pass --wide."
                % (width, height, ", ".join(sorted(ceiling.keys())))
            )
        max_frames = min(candidates)

    extra_conditions = sum(1 for c in conditions if c["frame_index"] != 0)
    effective_frames = num_frames + extra_conditions * _CEILING_FRAMES_PER_CONDITION

    if effective_frames > max_frames:
        raise mps_guard.HostSafetyError(
            "HOST SAFETY REFUSAL: %dx%d supports at most %d frames at the non-wide (0.82) budget, but this\n"
            "request asks for %d frames (effective %d after conditioning derate). Reduce num_frames to <= %d,\n"
            "choose a lower resolution, or pass --wide for the higher (0.87) budget."
            % (width, height, max_frames, num_frames, effective_frames, max_frames)
        )


def _read_request(run_dir):
    with open(os.path.join(run_dir, "request.json")) as f:
        return json.load(f)


def _stage1_encode(run_dir):
    """Encode prompt + negative prompt with the T5 text encoder only.

    Never instantiates the full pipeline. Resident weights: ~8.87 GiB
    (text_encoder in bf16). This process exits when the function returns,
    which is what actually releases that memory -- see the note near the
    top of this file about not adding del / gc.collect() / torch.mps.empty_cache() calls.
    """
    mps_guard.set_watermark(mps_guard.FRACTION_STAGE1)
    mps_guard.preflight("stage1", mps_guard.FRACTION_STAGE1, require_servers_down=True)

    request = _read_request(run_dir)

    with mps_guard.Sentinel("stage1", run_dir) as sent:
        import torch
        from transformers import T5EncoderModel, T5Tokenizer

        token = os.environ.get("HF_TOKEN")
        device = _pick_device()

        tok = T5Tokenizer.from_pretrained(MODEL_ID, subfolder="tokenizer", token=token)
        # dtype= (not torch_dtype=) -- transformers 5.15.1 renamed the arg.
        te = T5EncoderModel.from_pretrained(
            MODEL_ID, subfolder="text_encoder", dtype=torch.bfloat16, token=token
        )
        te.eval()
        te.to(device)

        # torch.no_grad() is load-bearing, not defensive. te.eval() only disables
        # dropout; without this the T5 forward retains an autograd graph across all 24
        # encoder layers for a backward pass that never comes, and doing it twice
        # (positive + negative) pushed peak MPS from the expected ~8.87 GiB to 13.09 GiB
        # and tripped the stage-1 cap. diffusers' own _get_t5_prompt_embeds has no
        # no_grad because it inherits one from LTXConditionPipeline.__call__, which is
        # decorated with @torch.no_grad(); replicating only the inner function loses it.
        @torch.no_grad()
        def _encode(text):
            # Replicates diffusers' _get_t5_prompt_embeds exactly.
            ti = tok(
                text,
                padding="max_length",
                max_length=MAX_SEQUENCE_LENGTH,
                truncation=True,
                add_special_tokens=True,
                return_tensors="pt",
            )
            mask = ti.attention_mask.bool().to(device)
            emb = te(ti.input_ids.to(device), attention_mask=mask)[0].to(
                dtype=torch.bfloat16, device=device
            )
            return emb, mask

        prompt_embeds, prompt_attention_mask = _encode(request["prompt"])
        negative_prompt_embeds, negative_prompt_attention_mask = _encode(
            request["negative_prompt"]
        )

        import diffusers
        import transformers

        torch.save(
            {
                "prompt_embeds": prompt_embeds.cpu(),
                "prompt_attention_mask": prompt_attention_mask.cpu(),
                "negative_prompt_embeds": negative_prompt_embeds.cpu(),
                "negative_prompt_attention_mask": negative_prompt_attention_mask.cpu(),
                "meta": {
                    "model_id": MODEL_ID,
                    "prompt": request["prompt"],
                    "negative_prompt": request["negative_prompt"],
                    "max_sequence_length": MAX_SEQUENCE_LENGTH,
                    "dtype": "bfloat16",
                    "diffusers_version": diffusers.__version__,
                    "transformers_version": transformers.__version__,
                },
            },
            os.path.join(run_dir, "embeds.pt"),
        )

    mps_guard.write_peaks(run_dir, "stage1", sent.peak)
    print("[ltx_video_skill] stage1: wrote %s" % os.path.join(run_dir, "embeds.pt"))


def _stage2_denoise(run_dir):
    """Load the transformer + VAE (no text encoder) and denoise to frames.

    Resident weights: 24.29 + 2.32 = 26.61 GiB.
    """
    request = _read_request(run_dir)
    fraction = mps_guard.FRACTION_STAGE2_WIDE if request["wide"] else mps_guard.FRACTION_STAGE2
    mps_guard.set_watermark(fraction)
    # LTX_SWEEP_RELAX_SUPPLY is set ONLY by tests/measure_ltx_ceiling.py for
    # measurement cells; the normal generate_video path never sets it, so
    # real runs keep the full G1b conjunction.
    skip_supply = os.environ.get("LTX_SWEEP_RELAX_SUPPLY") == "1"
    mps_guard.preflight("stage2", fraction, require_servers_down=True,
                        skip_supply_gate=skip_supply)

    with mps_guard.Sentinel("stage2", run_dir) as sent:
        import torch
        from diffusers import LTXConditionPipeline
        from diffusers.pipelines.ltx.pipeline_ltx_condition import LTXVideoCondition
        from diffusers.utils import load_image

        token = os.environ.get("HF_TOKEN")
        device = _pick_device()

        # torch_dtype= is correct here -- this is the diffusers API, not
        # transformers (stage1 above deliberately uses dtype= instead; do
        # not "fix" either one to match the other).
        # text_encoder must be passed as an explicit None (not omitted)
        # because LTXConditionPipeline._optional_components == []. This
        # means the 17.74 GiB of text-encoder shards are never read.
        pipeline = LTXConditionPipeline.from_pretrained(
            MODEL_ID,
            text_encoder=None,
            torch_dtype=torch.bfloat16,
            token=token,
        )
        pipeline.to(device.type)

        # Decode-memory levers, both enabled, in this order:
        pipeline.vae.enable_tiling()  # spatial only; sets use_tiling
        pipeline.vae.use_framewise_decoding = True  # temporal; no public setter in diffusers 0.40.0
        # A future diffusers upgrade could silently rename this private
        # attribute and revert to whole-tensor decode -- assert it stuck.
        assert pipeline.vae.use_framewise_decoding is True
        # Deliberately NOT calling pipeline.vae.enable_slicing(): it is a no-op
        # here, because AutoencoderKLLTXVideo.decode only consults use_slicing
        # when z.shape[0] > 1, and this pipeline always decodes at batch 1.
        # Payoff of framewise decoding: it slices 3 latent frames (~24 pixel
        # frames) per decode pass instead of all 7, roughly a 4.3x cut on
        # the widest decoder stage, at the cost of ~7x slower decode.
        # Correctness over speed.

        data = torch.load(os.path.join(run_dir, "embeds.pt"), map_location="cpu")
        if (
            data["meta"]["prompt"] != request["prompt"]
            or data["meta"]["negative_prompt"] != request["negative_prompt"]
        ):
            raise RuntimeError(
                "stale embeds.pt: it was encoded for prompt=%r negative_prompt=%r "
                "but request.json now asks for prompt=%r negative_prompt=%r"
                % (
                    data["meta"]["prompt"],
                    data["meta"]["negative_prompt"],
                    request["prompt"],
                    request["negative_prompt"],
                )
            )

        prompt_embeds = data["prompt_embeds"].to(device)
        prompt_attention_mask = data["prompt_attention_mask"].to(device)
        negative_prompt_embeds = data["negative_prompt_embeds"].to(device)
        negative_prompt_attention_mask = data["negative_prompt_attention_mask"].to(device)

        # prompt=None is mandatory -- check_inputs raises if both prompt and
        # prompt_embeds are given. prompt_attention_mask is mandatory
        # alongside prompt_embeds. All four embed/mask tensors are always
        # passed: at guidance_scale=1.0 the negatives are simply never
        # concatenated, so this is one code path with ~2 MiB of dead device
        # memory and zero branching. generator on CPU mirrors the pattern
        # already used in z_image_skill.py.
        # Conditioning images fully control the generated content -- frame 0 is hard-written into the latent
        # grid -- so an unsafe input essentially guarantees an unsafe output. Screening inputs is strictly more
        # protective and cheaper than screening outputs (fewer images, before the ~minutes-long denoise). The
        # stage-3 OUTPUT screening (content_safety.assert_frames_safe, ~line 574) is LIVE and active -- it is
        # NOT commented out. This stage-2 INPUT screening below is an optional, currently-disabled add-on that
        # can be enabled independently of stage-3; the two are not coupled, and enabling this one does not
        # require -- and must NOT be taken as license to -- disabling the live stage-3 output screening.
        #cond_images = [load_image(c["image_path"]) for c in _normalized_conditions(request)]
        #try:
        #    content_safety.assert_frames_safe(cond_images, skill="ltx_video_skill", prompt=request["prompt"])
        #except content_safety.ContentSafetyError:
        #    raise

        result = pipeline(
            conditions=[
                LTXVideoCondition(
                    image=load_image(c["image_path"]),
                    frame_index=c["frame_index"],
                    strength=c["strength"],
                )
                for c in _normalized_conditions(request)
            ],
            prompt=None,
            negative_prompt=None,
            prompt_embeds=prompt_embeds,
            prompt_attention_mask=prompt_attention_mask,
            negative_prompt_embeds=negative_prompt_embeds,
            negative_prompt_attention_mask=negative_prompt_attention_mask,
            width=request["width"],
            height=request["height"],
            num_frames=request["num_frames"],
            num_inference_steps=request["num_inference_steps"],
            guidance_scale=request["guidance_scale"],
            frame_rate=request["frame_rate"],
            generator=torch.Generator("cpu").manual_seed(request["seed"]),
            output_type="pil",
            max_sequence_length=MAX_SEQUENCE_LENGTH,
        )
        # The pipeline internally does latents = latents.to(prompt_embeds.dtype),
        # so the persisted bf16 dtype from stage1 governs the decode dtype.
        # This is load-bearing, not cosmetic.

        frames = result.frames[0]
        frames_dir = os.path.join(run_dir, "frames")
        os.makedirs(frames_dir, exist_ok=True)
        for i, frame in enumerate(frames):
            frame.save(os.path.join(frames_dir, "frame_%05d.png" % i))

    mps_guard.write_peaks(run_dir, "stage2", sent.peak)
    print("[ltx_video_skill] stage2: wrote %d frames to %s" % (len(frames), frames_dir))


def _stage3_screen_and_export(run_dir):
    """Screen frames for unsafe content, then export to mp4 if allowed.

    No diffusion weights are resident in this process; the NSFW classifier
    is ~86M params fp32 pinned to CPU.
    """
    mps_guard.set_watermark(mps_guard.FRACTION_STAGE3)
    mps_guard.preflight("stage3", mps_guard.FRACTION_STAGE3, require_servers_down=False)

    request = _read_request(run_dir)

    with mps_guard.Sentinel("stage3", run_dir) as sent:
        import content_safety
        from diffusers.utils import export_to_video
        from PIL import Image

        frames_dir = os.path.join(run_dir, "frames")
        paths = sorted(glob.glob(os.path.join(frames_dir, "*.png")))
        frames = [Image.open(p).convert("RGB") for p in paths]

        if len(frames) != request["num_frames"]:
            raise RuntimeError(
                "partial frame set in %s: found %d frames, expected %d. "
                "A partial frame set means stage2 was aborted mid-flight and "
                "must not be treated as success." % (frames_dir, len(frames), request["num_frames"])
            )

        try:
            content_safety.assert_frames_safe(
                frames, skill="ltx_video_skill", prompt=request["prompt"]
            )
        except content_safety.ContentSafetyError:
            # No flagged pixels persist -- honours the "saves nothing" contract.
            shutil.rmtree(frames_dir)
            raise

        if request["output_path"] is not None:
            # imageio / imageio_ffmpeg are NOT installed (cv2 4.12.0 and av
            # 15.1.0 are), so this falls through to diffusers'
            # _legacy_export_to_video, which writes mp4v via cv2.VideoWriter.
            # Functional; lower quality than h264. Do not add a dependency
            # here.
            export_to_video(frames, request["output_path"], fps=request["fps"])

    mps_guard.write_peaks(run_dir, "stage3", sent.peak)
    # "screened" is load-bearing: only print it on the path where
    # assert_frames_safe actually ran and did not raise above -- never
    # reintroduce this as a bare print if screening is ever conditionally skipped.
    summary = "[ltx_video_skill] stage3: screened %d frames" % len(frames)
    if request["output_path"] is not None:
        summary += ", exported to %s" % request["output_path"]
    print(summary)


def _sentinel_abort_line(run_dir, stage_name):
    path = os.path.join(run_dir, "mem_%s.jsonl" % stage_name)
    try:
        with open(path) as f:
            for line in f:
                if '"sentinel_abort"' in line:
                    return line.strip()
    except OSError:
        pass
    return "(no sentinel_abort record found in %s)" % path


def _release_page_cache(run_dir, image_path, prompt, output_path):
    """Evict the page cache between stage 1 and stage 2.

    Stage 1 mmaps 17.74 GiB of T5 shards. Measured on a real run, this
    moved `filebacked` from 0.71 to 19.05 GiB and `active` from 2.21 to
    11.32, dropping psutil.available from 40.40 to 31.30 GiB -- which then
    failed stage 2's gate (required=32.20) by 0.90 GiB. The two stages
    interfere through the filesystem cache, and waiting does not help:
    availability was polled for 140 s and never recovered.

    An in-process alternative -- committing and freeing MPS memory to
    force eviction -- was considered and rejected: eviction only begins
    once free memory is consumed, so recovering the measured 0.90 GiB
    shortfall that way would have required roughly a 21 GiB commitment,
    against a real margin of ~35 GiB. `sudo purge` does the same eviction
    directly and cheaply.

    Wrapped in try/except so a failure here can never break a run that
    would otherwise succeed.
    """
    try:
        before = mps_guard.snapshot()
        # -n: non-interactive. Without it, a missing cached sudo credential
        # would block on a password prompt that never arrives in this
        # context, rather than failing immediately.
        proc = subprocess.run(
            ["/usr/bin/sudo", "-n", "/usr/sbin/purge"],
            capture_output=True,
            text=True,
            timeout=120,
        )
        if proc.returncode == 0:
            after = mps_guard.snapshot()
            print(
                "[ltx_video_skill] page cache released: avail %.2f -> %.2f GiB, "
                "filebacked %.2f -> %.2f GiB"
                % (
                    before["avail_gib"],
                    after["avail_gib"],
                    before["filebacked_gib"],
                    after["filebacked_gib"],
                )
            )
        else:
            resume_line = '  python3 ltx_video_skill.py --resume %s %s "%s"' % (
                run_dir,
                image_path,
                prompt,
            )
            if output_path:
                resume_line += " %s" % output_path
            sys.stderr.write(
                "[ltx_video_skill] note: could not run `sudo purge` (no cached credentials).\n"
                "Stage 1 leaves ~18 GiB of the T5 shards in the filesystem cache, which lowers\n"
                "reported available memory and may cause stage 2 to be refused. If that happens,\n"
                "run `sudo purge` in a terminal and resume without redoing stage 1:\n"
                + resume_line
                + "\n"
            )
    except Exception as e:
        print("[ltx_video_skill] note: _release_page_cache failed (continuing): %s" % e)


def generate_video(image_path: str, prompt: str = "", output_path: str = None, **kwargs):
    """Generate a short video from a static image using LTX-Video 13B distilled.

    Runs three subprocess stages in order (text encoding, denoising, safety
    screening + export), each with its own memory ceiling -- see the module
    docstring for why.

    Args:
        image_path: Path to the input image (local file path or URL).
        prompt: Optional text description guiding the motion/content.
        output_path: Optional file path to save the MP4. If given, the video
            is saved there.
        **kwargs: width, height, num_frames, num_inference_steps,
            guidance_scale, fps, frame_rate, negative_prompt, seed (default
            0), wide (default False, opt-in wider stage2 activation budget),
            resume_run_dir (default None; see below).

    When resume_run_dir is given, stage 1 (and stage 2, if its frames are
    already complete) are skipped in favour of the existing run directory's
    outputs, rather than starting a fresh run. request.json is not
    rewritten; prompt and image_path are only checked against it for a
    stale-embeds mismatch.

    Returns:
        list[PIL.Image.Image]: the generated video frames.
    """
    width = kwargs.get("width", DEFAULT_WIDTH)
    height = kwargs.get("height", DEFAULT_HEIGHT)
    num_frames = kwargs.get("num_frames", DEFAULT_NUM_FRAMES)
    num_inference_steps = kwargs.get("num_inference_steps", DEFAULT_STEPS)
    guidance_scale = kwargs.get("guidance_scale", DEFAULT_GUIDANCE)
    fps = kwargs.get("fps", DEFAULT_FPS)
    frame_rate = kwargs.get("frame_rate", DEFAULT_FRAME_RATE)
    negative_prompt = kwargs.get("negative_prompt", DEFAULT_NEGATIVE_PROMPT)
    seed = kwargs.get("seed", 0)
    wide = kwargs.get("wide", False)
    allow_override = kwargs.get("allow_override", False)
    resume_run_dir = kwargs.get("resume_run_dir", None)
    last_frame_path = kwargs.get("last_frame_path", None)
    keyframes = kwargs.get("keyframes", None)

    _validate_geometry(width, height, num_frames)

    # Assemble the conditions list: primary (frame 0), then last-frame (if
    # any), then keyframes in the order given. URL image paths must not be
    # passed through os.path.abspath -- guard each abspath call so today's
    # URL support for the primary image keeps working.
    conditions = [
        {
            "image_path": image_path if "://" in image_path else os.path.abspath(image_path),
            "frame_index": 0,
            "strength": 1.0,
        }
    ]
    if last_frame_path is not None:
        conditions.append(
            {
                "image_path": last_frame_path
                if "://" in last_frame_path
                else os.path.abspath(last_frame_path),
                "frame_index": num_frames - 1,
                "strength": 1.0,
            }
        )
    for kf in (keyframes or []):
        kf_image_path = kf["image_path"]
        conditions.append(
            {
                "image_path": kf_image_path
                if "://" in kf_image_path
                else os.path.abspath(kf_image_path),
                "frame_index": int(kf["frame_index"]),
                "strength": float(kf.get("strength", 1.0)),
            }
        )
    _validate_conditions(conditions, num_frames)
    # --allow-override bypasses ONLY this advisory ceiling-table pre-check.
    # It does not touch mps_guard.preflight (G0/G0b/G1a/G1b/G2), the MPS
    # watermark cap (set_per_process_memory_fraction), or the stage-2
    # Sentinel -- those run in the stage-2 subprocess and remain the
    # authoritative runtime backstop, so an overridden run that is genuinely
    # too big still fails as a clean OOM-at-cap or sentinel abort, not a
    # frozen host.
    if allow_override:
        sys.stderr.write("[ltx_video_skill] --allow-override: skipping the ceiling pre-check "
                         "(mps_guard watermark cap + sentinel remain the runtime backstop; "
                         "an over-budget run will still fail cleanly, not freeze).\n")
    elif resume_run_dir is not None:
        sys.stderr.write("[ltx_video_skill] resume: ceiling pre-check skipped (geometry fixed by "
                         "the existing run; mps_guard remains the runtime backstop).\n")
    else:
        _check_ceiling(width, height, num_frames, conditions, wide)

    skip_stage1 = False
    skip_stage2 = False

    # Resume reads the existing request.json and does not rewrite it, so the
    # `conditions` assembled above from this call's last_frame_path/keyframes
    # is not used in the resume path below -- the run's original conditions
    # (or, for a legacy run, the frame-0 image_path) are what stage 2 uses.
    # Because embeds.pt is text-only (prompt/negative_prompt), changing
    # conditioning images does not invalidate a resume. To change keyframes
    # on a resumed run, edit that run's request.json directly; the normal
    # path is a fresh run.
    if resume_run_dir is not None:
        run_dir = os.path.abspath(resume_run_dir)
        request_path = os.path.join(run_dir, "request.json")
        if not os.path.isdir(run_dir) or not os.path.isfile(request_path):
            raise ValueError(
                "resume_run_dir=%r does not exist or has no request.json" % run_dir
            )

        request = _read_request(run_dir)

        if request["prompt"] != prompt:
            raise ValueError(
                "resume_run_dir=%r request.json has prompt=%r, which does not match "
                "the given prompt=%r -- refusing rather than silently generating from "
                "stale embeds" % (run_dir, request["prompt"], prompt)
            )
        abs_request_image_path = os.path.abspath(request["image_path"])
        abs_image_path = os.path.abspath(image_path)
        if abs_request_image_path != abs_image_path:
            raise ValueError(
                "resume_run_dir=%r request.json has image_path=%r, which does not match "
                "the given image_path=%r -- refusing rather than silently generating from "
                "stale embeds" % (run_dir, abs_request_image_path, abs_image_path)
            )

        embeds_path = os.path.join(run_dir, "embeds.pt")
        if os.path.exists(embeds_path):
            skip_stage1 = True
            print("[ltx_video_skill] resume: reusing existing embeds.pt, skipping stage 1")

        frames_dir = os.path.join(run_dir, "frames")
        existing_frames = sorted(glob.glob(os.path.join(frames_dir, "*.png")))
        if len(existing_frames) == request["num_frames"]:
            skip_stage2 = True
            print("[ltx_video_skill] resume: reusing existing frames/, skipping stage 2")
        elif existing_frames:
            print(
                "[ltx_video_skill] resume: clearing partial frames/ (%d of %d PNGs found)"
                % (len(existing_frames), request["num_frames"])
            )
            shutil.rmtree(frames_dir)
    else:
        workspace = os.path.dirname(os.path.abspath(__file__))
        run_id = "%s-%s" % (
            datetime.datetime.now(datetime.timezone.utc).strftime("%Y%m%dT%H%M%SZ"),
            uuid.uuid4().hex[:8],
        )
        run_dir = os.path.join(workspace, RUNS_SUBDIR, run_id)
        os.makedirs(run_dir)

        request = {
            "image_path": conditions[0]["image_path"],
            "prompt": prompt,
            "negative_prompt": negative_prompt,
            "output_path": output_path,
            "width": width,
            "height": height,
            "num_frames": num_frames,
            "num_inference_steps": num_inference_steps,
            "guidance_scale": guidance_scale,
            "fps": fps,
            "frame_rate": frame_rate,
            "seed": seed,
            "wide": wide,
            "allow_override": allow_override,
            "conditions": conditions,
        }
        with open(os.path.join(run_dir, "request.json"), "w") as f:
            json.dump(request, f, indent=2)

    for n in (1, 2, 3):
        if n == 1 and skip_stage1:
            continue
        if n == 2 and skip_stage2:
            continue

        proc = subprocess.run(
            [sys.executable, os.path.abspath(__file__), "--stage", str(n), "--run-dir", run_dir],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            check=False,
        )
        print(proc.stdout)
        with open(os.path.join(run_dir, "stage%d.log" % n), "w") as f:
            f.write(proc.stdout)

        if proc.returncode == mps_guard.SENTINEL_EXIT_CODE:
            raise RuntimeError(
                "stage%d aborted by mps_guard sentinel: %s"
                % (n, _sentinel_abort_line(run_dir, "stage%d" % n))
            )
        if proc.returncode != 0:
            # A refused preflight gate prints its own HostSafetyError
            # traceback in the child log AND (before this change) the
            # parent re-printed the identical text as "last 40 lines of
            # log" -- the actionable line ended up buried twice. When the
            # refusal marker is present, surface only that block; fall back
            # to the traceback-tail behaviour for a genuine crash. The
            # marker appears mid-line in the child traceback, prefixed by
            # the exception class name (e.g. "mps_guard.HostSafetyError: "),
            # so a substring match is required (startswith would never
            # match), and that prefix is sliced off before surfacing.
            log_lines = (proc.stdout or "").splitlines()
            marker = "HOST SAFETY REFUSAL:"
            refusal_index = None
            for i, log_line in enumerate(log_lines):
                if marker in log_line:
                    refusal_index = i
                    first = log_line[log_line.index(marker):]
                    break
            if refusal_index is not None:
                refusal_block = "\n".join([first] + log_lines[refusal_index + 1:])
                raise RuntimeError(
                    "stage%d refused by mps_guard:\n\n%s" % (n, refusal_block)
                )
            tail = "\n".join(log_lines[-40:])
            raise RuntimeError(
                "stage%d failed with exit code %d, last 40 lines of log:\n%s"
                % (n, proc.returncode, tail)
            )

        if n == 1:
            _release_page_cache(run_dir, image_path, prompt, output_path)

    frames_dir = os.path.join(run_dir, "frames")
    paths = sorted(glob.glob(os.path.join(frames_dir, "*.png")))
    from PIL import Image

    frames = [Image.open(p).convert("RGB") for p in paths]

    generate_video.last_run_dir = run_dir
    print("[ltx_video_skill] run_dir: %s" % run_dir)
    return frames


if __name__ == "__main__":
    if "--stage" in sys.argv:
        parser = argparse.ArgumentParser()
        parser.add_argument("--stage", type=int, choices=[1, 2, 3], required=True)
        parser.add_argument("--run-dir", dest="run_dir", required=True)
        parser.add_argument("--wide", action="store_true")
        args = parser.parse_args()
        if args.stage == 1:
            _stage1_encode(args.run_dir)
        elif args.stage == 2:
            _stage2_denoise(args.run_dir)
        elif args.stage == 3:
            _stage3_screen_and_export(args.run_dir)
        sys.exit(0)

    USAGE = (
        'Usage: python3 ltx_video_skill.py [--resume RUN_DIR] [--last-frame PATH]\n'
        '       [--keyframe PATH:INDEX[:STRENGTH]]... [--width N] [--height N]\n'
        '       [--num-frames N] [--fps N] [--frame-rate N] [--wide] [--allow-override]\n'
        '       <image_path> ["<prompt>"] [output_path]'
    )

    # --resume is only valid in this positional form (never with --stage,
    # handled above). Scanned and stripped BEFORE the positional handling
    # below so the existing three-positional contract is untouched when
    # --resume is absent.
    resume_run_dir = None
    if "--resume" in sys.argv:
        idx = sys.argv.index("--resume")
        if idx + 1 >= len(sys.argv):
            print(USAGE)
            sys.exit(1)
        resume_run_dir = sys.argv[idx + 1]
        sys.argv[idx : idx + 2] = []

    # --last-frame and --keyframe are scanned and stripped BEFORE the
    # positional handling below, in the same style as --resume above.
    last_frame_path = None
    if "--last-frame" in sys.argv:
        idx = sys.argv.index("--last-frame")
        if idx + 1 >= len(sys.argv):
            print(USAGE)
            sys.exit(1)
        last_frame_path = sys.argv[idx + 1]
        sys.argv[idx : idx + 2] = []

    keyframes = []
    while "--keyframe" in sys.argv:
        idx = sys.argv.index("--keyframe")
        if idx + 1 >= len(sys.argv):
            print(USAGE)
            sys.exit(1)
        spec = sys.argv[idx + 1]
        sys.argv[idx : idx + 2] = []
        try:
            keyframes.append(_parse_keyframe_spec(spec))
        except ValueError as e:
            print(str(e), file=sys.stderr)
            sys.exit(2)

    # --fps, --frame-rate, and --wide are scanned and stripped BEFORE the
    # positional handling below, in the same style as --resume above.
    fps_arg = None
    if "--fps" in sys.argv:
        idx = sys.argv.index("--fps")
        if idx + 1 >= len(sys.argv):
            print(USAGE)
            sys.exit(1)
        try:
            fps_arg = int(sys.argv[idx + 1])
        except ValueError:
            print("--fps requires an integer", file=sys.stderr)
            sys.exit(2)
        sys.argv[idx : idx + 2] = []

    frame_rate_arg = None
    if "--frame-rate" in sys.argv:
        idx = sys.argv.index("--frame-rate")
        if idx + 1 >= len(sys.argv):
            print(USAGE)
            sys.exit(1)
        try:
            frame_rate_arg = int(sys.argv[idx + 1])
        except ValueError:
            print("--frame-rate requires an integer", file=sys.stderr)
            sys.exit(2)
        sys.argv[idx : idx + 2] = []

    wide_arg = False
    if "--wide" in sys.argv:
        wide_arg = True
        sys.argv.remove("--wide")

    allow_override_arg = False
    if "--allow-override" in sys.argv:
        allow_override_arg = True
        sys.argv.remove("--allow-override")

    width_arg = None
    if "--width" in sys.argv:
        idx = sys.argv.index("--width")
        if idx + 1 >= len(sys.argv):
            print(USAGE)
            sys.exit(1)
        try:
            width_arg = int(sys.argv[idx + 1])
        except ValueError:
            print("--width requires an integer", file=sys.stderr)
            sys.exit(2)
        sys.argv[idx : idx + 2] = []

    height_arg = None
    if "--height" in sys.argv:
        idx = sys.argv.index("--height")
        if idx + 1 >= len(sys.argv):
            print(USAGE)
            sys.exit(1)
        try:
            height_arg = int(sys.argv[idx + 1])
        except ValueError:
            print("--height requires an integer", file=sys.stderr)
            sys.exit(2)
        sys.argv[idx : idx + 2] = []

    num_frames_arg = None
    if "--num-frames" in sys.argv:
        idx = sys.argv.index("--num-frames")
        if idx + 1 >= len(sys.argv):
            print(USAGE)
            sys.exit(1)
        try:
            num_frames_arg = int(sys.argv[idx + 1])
        except ValueError:
            print("--num-frames requires an integer", file=sys.stderr)
            sys.exit(2)
        sys.argv[idx : idx + 2] = []

    if len(sys.argv) < 2:
        print(USAGE)
        sys.exit(1)
    image_path = sys.argv[1]
    prompt = sys.argv[2] if len(sys.argv) > 2 else ""
    out = sys.argv[3] if len(sys.argv) > 3 else "ltx_video_output.mp4"
    extra = {
        "resume_run_dir": resume_run_dir,
        "last_frame_path": last_frame_path,
        "keyframes": keyframes,
        "wide": wide_arg,
    }
    extra["allow_override"] = allow_override_arg
    if fps_arg is not None:
        extra["fps"] = fps_arg
    if frame_rate_arg is not None:
        extra["frame_rate"] = frame_rate_arg
    if width_arg is not None:
        extra["width"] = width_arg
    if height_arg is not None:
        extra["height"] = height_arg
    if num_frames_arg is not None:
        extra["num_frames"] = num_frames_arg
    generate_video(
        image_path,
        prompt,
        output_path=out,
        **extra,
    )
